import type { Metadata } from "next";
import "./globals.css";
import 'animate.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black text-white">
        <div className="container">
          {children}
        </div>
      </body>
    </html>
  );
}
