import React from 'react'
import Card from './card.component'
import { GlobalComponents } from '../global'
const ReachHumans = () => {
  return (
    <div className='reach-humans my-12'>
      <h2 className='my-5 md:ml-[55px] text-5xl md:w-1/3'>Reach Humans not spam folders</h2>
      <div className='md:gap-1 md:flex-wrap md:flex md:justify-around md:items-start'>
        <Card icon="/assets/card-icon-1.png" title="Proactive blocklist tracking" paragraph="Be the first to know if your domain is added to a DNSBLs such as those offered by Spamhaus with removal requests generated by Resend." />
        <Card icon="/assets/card-icon-2.png" title="Faster Time to Inbox" paragraph="Send emails from the region closest to your users. Reduce delivery latency with North American, South American, and European regions." />
        <Card icon="/assets/card-icon-3.png" title="Build confidence with BIMI" paragraph="Showcase your logo and company branding with BIMI. Receive guidance to obtain a VMC - the email equivalent of a checkmark on social media." />
        <Card icon="/assets/card-icon-4.png" title="Managed Dedicated IPs" paragraph="Get a fully managed dedicated IP that automatically warms up and autoscales based on your sending volume, no waiting period." />
        <Card icon="/assets/card-icon-5.png" title="Dynamic suppression list" paragraph="Prevent repeated sending to recipients who no longer want your email and comply with standards like the CAN-SPAM Act and others." />
        <Card icon="/assets/card-icon-6.png" title="IP and domain monitoring" paragraph="Monitor your DNS configuration for any errors or regressions. Be notified of any changes that could hinder your deliverability." />
        <Card icon="/assets/card-icon-7.png" title="Verify DNS records" paragraph="Protect your reputation by verifying your identity as a legitimate sender. Secure your email communication using DKIM and SPF." />
        <Card icon="/assets/card-icon-8.png" title="Battle-tested infrastructure" paragraph="Rely on a platform of reputable IP's used by trustworthy senders with distributed workloads across different IP pools." />
        <Card icon="/assets/card-icon-9.png" title="Prevent spoofing with DMARC" paragraph="Avoid impersonation by creating DMARC policies and instructing inbox providers on how to treat unauthenticated email." />
      </div>
      <GlobalComponents.Border />
    </div>
  )
}

export default ReachHumans
